{% set name = "heroicons" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/heroicons-{{ version }}.tar.gz
  sha256: d1b0787e233b6e59583fc1877d77709e21941d2ad0fadb53a27c65a3691d7ebf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8

test:
  imports:
    - heroicons
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/adamchainz/heroicons
  summary: Use heroicons in your Django and Jinja templates.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
